### ISSUE TITLE
go新手上手有点不知道应该怎么操作

### ISSUE THREAD

**Issue by qikong333** [snowlyg/iris-admin-rbac#1]
作者您好，我是刚学go不久，算接口仔的程度吧，然后这个东西拿上手不知道应该怎么使用好，文档很精简，但是我可能要写可看着操作的视频之类的东西，请问哪里可以找到啊

**Comment by snowlyg** [comment]
@qikong333 你是小看 go 方面的视频教程吗？可以去 b 站或者油管找找。
